version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2022.05 # Primary execution image
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.14
      - run:
          name: build-docker-image
          command: docker build -t enochval/docker-react -f Dockerfile.dev .
      - run:
          name: run-test
          command: docker run enochval/docker-react npm run test -- --converage